# Generated by Django 4.2.7 on 2023-12-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_remove_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
    ]
