# Generated by Django 4.2.7 on 2024-08-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_images_image_alter_product_pic"),
        ("comment", "0002_remove_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.product",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(default="user", max_length=255),
        ),
    ]
