# Generated by Django 4.2.7 on 2023-11-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
        migrations.DeleteModel(
            name="Sliders",
        ),
    ]
