# Generated by Django 4.2.7 on 2024-09-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="color_code",
            field=models.CharField(default="", max_length=255),
        ),
    ]
