# Generated by Django 4.2.7 on 2024-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
